### ISSUE TITLE
Missing comma results in syntax error

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminus-server#105]
https://github.com/terminusdb/terminus-server/blob/c9e40f72af6c629de4f671f8b5d60e78abab5d04/library/validate.pl#L110

It should be:

```prolog
descriptor: Descriptor,
```

**Comment by rrooij** [comment]
Thanks, you're absolutely right! 

The `hub` branch has a lot of work in progress that is sometimes not finished. That's why there may be syntax errors left in commits and the like.
