### ISSUE TITLE
Typo in predicate name

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminus-server#115]
The following is an obvious typo:

https://github.com/terminusdb/terminus-server/blob/969aa22d92c7018bc27f09fce6b3d01a2614c886/server/routes.pl#L780

Should it be `terminus_database` or `terminus_database_name`?

Reported by the Logtalk linter as:

```text
*     Unknown predicate called but not defined: terminus_databasoe/1
*       while compiling object routes
*       in file /Users/pmoura/terminus-server/server/routes.pl between lines 770-792
```

**Comment by GavinMendelGleason** [comment]
Indeed that's wrong. The logic is also somewhat wrong though. We need to open Terminus_DB once so we have a shared view in all of those predicates. 

```
Descriptor = terminus_descriptor{},
open_descriptor(Descriptor, Terminus_DB),
...
```

Should probably go at the top of the predicate.

**Comment by rrooij** [comment]
Typo has been fixed! Thanks.
