### ISSUE TITLE
Init script should replace existing console index

### ISSUE THREAD

**Issue by kevinchekovfeeney** [terminusdb/terminus-server#82]
The init script currently does not update the index html file produced by the index.tpl file template. This means that on updates, any updates to the html template will not be updated

This caused a bad problem with release of 1.1.0 when the docker would not work when installed in the same location as a previous install and had myself and gavin up till all hours trying to fix it in production

**Comment by rrooij** [comment]
Was just looking through the issues and this has been solved now. The index.html is generated each time when the db_util script is run.
