### ISSUE TITLE
URL encoding - %20 - are not interpreted correctly in ID URLs

### ISSUE THREAD

**Issue by kevinchekovfeeney** [terminusdb/terminus-server#83]
The ids of documents, especially those generated by idgen can contain URL encodings of spaces "%20" these are automatically interpolated into their url decoding as spaces and they return an error. The problem shows up in the document api - there is no problem in query. The fix should reverse the encoding used in the Idgen

**Comment by GavinMendelGleason** [comment]
Fixed in dev
